config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "cocktails#index"
  resources :cocktails, only: [:new, :create, :show, :index] do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  has_many :ingredients, through: :doses
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates_uniqueness_of :cocktail, :scope => :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true, length: {minimum: 5}
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: 1..5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :photo)
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@review.cocktail)
    else
      render :new
    end
  end

  def review_params
    params.require(:review).permit(:content, :rating, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="container w-80">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-4 mt-3">
        <%= link_to cocktail_path(cocktail.id) do %>
          <div class="cocktail-card"  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, height: 300, width: 400, crop: :fill %>')">
            <h2><%= cocktail.name %></h2>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container w-50 mt-3">
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :description, as: :text %>
    <%= f.input :photo, as: :file %>
    <%= f.submit :Create!, class:"btn btn-primary w-100 mt-2" %>
  <% end %>
</div>

app/views/cocktails/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @cocktail.photo.key %>');">
  <div class="container">
    <h1><%= @cocktail.name %></h1>
  </div>
</div>
<div class="container mt-3">
  <div class="row">
    <div class="col-7 mr-3 p-3" style=" box-shadow: 1px 1px 1px 1px rgba(0, 0, 0, 0.2);">
      <h2>Description</h2>
      <p><%= @cocktail.description %></p>
    </div>
    <div class="col-4 p-3" style=" box-shadow: 1px 1px 1px 1px rgba(0, 0, 0, 0.2);">
      <h2>Ingredients</h2>
      <ul>
        <% @cocktail.doses.each do |dose| %>
          <li><%= dose.description %> <strong><%= dose.ingredient.name %></strong> 
          <%= link_to "Delete", dose_path(dose), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-outline-danger" %>
          </li>
        <% end %>
      </ul>
      <%= link_to "Add Ingredient", new_cocktail_dose_path(@cocktail), class:"btn btn-outline-warning w-100" %>
    </div>
    <div class="col-8 p-3 mx-auto mt-3" style=" box-shadow: 1px 1px 1px 1px rgba(0, 0, 0, 0.2);">
    <h2>Reviews</h2>
    <ul class="mb-3 pl-0">
      <% @cocktail.reviews.each do |review| %>
        <li class="list-group-item mb-2"><%= review.content %>
        <% review.rating.times do %>
          <i class="fas fa-star stars"></i>
        <% end %>
        <% (5 - review.rating).times do %>
          <i class="fas fa-star not-stars"></i>
        <% end %>
        </li>
      <% end %>
    </ul>
    <%= link_to "Add Review", new_cocktail_review_path(@cocktail), class:"btn btn-outline-warning w-100" %>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container w-50 mt-3">
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit :Add!, class: "btn btn-primary rounded w-100 mt-3" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <nav class="navbar navbar-dark bg-dark">
    <div class="container-fluid">
      <%= link_to "Los tragos de Nati y Guido", cocktails_path, class:"navbar-brand" %>
      <%= link_to "Add a Cocktail", new_cocktail_path, class:"navbar-brand btn btn-outline-danger" %>
    </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="container w-50 mt-3">
  <%= simple_form_for [@cocktail, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: 1..5 %>
    <%= f.submit :Send!, class: "btn btn-primary rounded w-100 mt-3" %>
  <% end %>
</div>